name: event-camera
channels:
  - <unknown>
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_1
  - decorator=4.4.2=py_0
  - freetype=2.9.1=h8a8886c_1
  - future=0.18.2=py37_0
  - intel-openmp=2020.0=166
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.16.0=py37_1
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - ncurses=6.2=he6710b0_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.1.1e=h7b6447c_0
  - parso=0.6.2=py_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=20.0.2=py37_1
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py37_0
  - pygments=2.6.1=py_0
  - python=3.7.7=hcf32534_0_cpython
  - readline=8.0=h7b6447c_0
  - setuptools=46.1.1=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torch=1.5.0a0+ac639d9=py37h39e3cac_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.8=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - cachetools==4.0.0
    - chardet==3.0.4
    - google-auth==1.12.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.27.2
    - idna==2.9
    - markdown==3.2.1
    - numpy==1.18.2
    - oauthlib==3.1.0
    - opencv-python==4.2.0.32
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytorch-lightning==0.7.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - tensorboard==2.2.0
    - tensorboard-plugin-wit==1.6.0.post2
    - torchvision==0.5.0
    - tqdm==4.43.0
    - urllib3==1.25.8
    - werkzeug==1.0.0
prefix: /home/gianscarpe/anaconda3/envs/event-camera

